apiVersion: v1
kind: Secret
metadata:
  name: atomicly-secrets
  namespace: atomicly-local
type: Opaque
stringData:
  database-url: postgresql://postgres:postgres@host.docker.internal:55432/atomicly?schema=public
  auth-secret: local-kubernetes-auth-secret-replace-before-shared-use
