export interface Lesson {
  id: number;
  chapter: string;
  title: string;
  quote: string;
  body: string;
  takeaway: string;
  practice: string;
  minutes: number;
}

export const LESSONS: Lesson[] = [
  {
    id: 1, chapter: 'Foundations', title: 'You do not rise to the level of your goals',
    quote: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    body: 'Goals set the direction; systems get you there. A goal of "read more" without a system (a book on the desk, a fixed time, a 2-page minimum) leaves you guessing every day. The system removes the daily decision.',
    takeaway: 'Stop polishing the goal. Polish the system that produces it.',
    practice: 'Pick one habit you keep "trying" to do. Write down the system it would need.',
    minutes: 2,
  },
  {
    id: 2, chapter: 'Foundations', title: 'The 1% rule',
    quote: 'Habits are the compound interest of self-improvement.',
    body: '1% better every day for a year = 37× better. 1% worse = nearly zero. Most days the gain is invisible — the math only shows up months later. This is why habits feel pointless before they feel inevitable.',
    takeaway: 'Optimize for showing up, not for the result of any single day.',
    practice: 'Plot your check-ins for the past 30 days. The line is the proof.',
    minutes: 2,
  },
  {
    id: 3, chapter: 'Foundations', title: 'The plateau of latent potential',
    quote: 'Habits often appear to make no difference until you cross a critical threshold.',
    body: "An ice cube doesn't melt at 31° or 30°. Then at 32° it transforms. Habits sit on a long flat plateau before the breakthrough. Quitting at month two is quitting one degree before the melt.",
    takeaway: 'When progress feels invisible, you are still inside the plateau, not outside the work.',
    practice: 'Write down the date you started a current habit. Commit to one more month.',
    minutes: 2,
  },
  {
    id: 4, chapter: 'Identity', title: 'Outcome vs. process vs. identity',
    quote: 'The most effective way to change your habits is to focus on who you wish to become.',
    body: "Three layers: outcomes (what you get), processes (what you do), identity (what you believe). Most people start with outcomes. Lasting change starts at identity. \"I am a runner\" beats \"I want to lose 10 lbs\" every time.",
    takeaway: "Don't pick a goal. Pick a person. Then act like them.",
    practice: 'Rewrite one of your habits as an identity statement: "I am someone who ___".',
    minutes: 3,
  },
  {
    id: 5, chapter: 'Identity', title: 'Every action is a vote',
    quote: 'Every action you take is a vote for the type of person you wish to become.',
    body: "No single vote decides an election; no single check-in defines you. But majorities accumulate. Each repetition is a small piece of evidence you give yourself: \"this is who I am.\"",
    takeaway: "You don't have to be perfect. You just have to win the majority of votes.",
    practice: "Open the Identity ledger and count the votes you've cast this month.",
    minutes: 2,
  },
  {
    id: 6, chapter: 'Identity', title: 'Two-step identity change',
    quote: 'Decide the type of person you want to be. Prove it to yourself with small wins.',
    body: "Identity emerges from habits, not the other way around. You believe you're a writer because you wrote 100 days in a row, not because you declared it. The proof comes first; the identity comes second.",
    takeaway: 'Belief without evidence collapses. Build the evidence pile.',
    practice: "Name one identity you're building. List 3 actions that would be evidence.",
    minutes: 3,
  },
  {
    id: 7, chapter: '1st Law · Make it obvious', title: 'The Habits Scorecard',
    quote: 'The first step to changing bad habits is to be on the lookout for them.',
    body: "Many habits are so automatic you stop noticing them. List everything you do in a typical day, then mark each + (helpful), − (harmful), or = (neutral). Awareness is the prerequisite for change.",
    takeaway: "You can't change a habit you can't see.",
    practice: 'Score 10 things you did today. Notice anything?',
    minutes: 4,
  },
  {
    id: 8, chapter: '1st Law · Make it obvious', title: 'Implementation intentions',
    quote: 'When and where will I do this?',
    body: 'A study found people who wrote "I will exercise at [TIME] in [PLACE]" were 2–3× more likely to follow through. Vague plans collide with reality; specific ones survive it.',
    takeaway: "Don't say \"more\". Say when and where.",
    practice: 'Rewrite a habit as: "I will [BEHAVIOR] at [TIME] in [LOCATION]".',
    minutes: 2,
  },
  {
    id: 9, chapter: '1st Law · Make it obvious', title: 'Habit stacking',
    quote: 'After [CURRENT HABIT], I will [NEW HABIT].',
    body: "New habits ride the rails of old ones. Coffee → vitamins. Brush teeth → meditate. The existing habit is the cue you don't need to remember.",
    takeaway: "Don't fight for new attention. Borrow attention you already pay.",
    practice: "Pick a habit. What's the existing rail you can stack it onto?",
    minutes: 2,
  },
  {
    id: 10, chapter: '1st Law · Make it obvious', title: 'Environment > motivation',
    quote: 'Environment is the invisible hand that shapes human behavior.',
    body: "You eat what's on the counter. You scroll what's on your home screen. The simplest behavior change isn't self-discipline — it's rearranging the room so the right thing is the obvious thing.",
    takeaway: 'Design the space. The space designs you back.',
    practice: 'Move one item this week to make a habit easier or harder.',
    minutes: 3,
  },
  {
    id: 11, chapter: '2nd Law · Make it attractive', title: 'Temptation bundling',
    quote: 'Pair an action you want to do with an action you need to do.',
    body: 'Only watch your favorite show while on the treadmill. Only listen to the podcast while walking. Bundling moves the craving onto the habit, so the habit becomes the gateway to the reward.',
    takeaway: 'Anchor a craving you already have to a habit you don\'t yet have.',
    practice: 'List one "want" + one "need". Bundle them this week.',
    minutes: 2,
  },
  {
    id: 12, chapter: '2nd Law · Make it attractive', title: 'Join the right tribe',
    quote: 'We imitate the close, the many, and the powerful.',
    body: 'Habits become attractive when we see others around us doing them. The fastest way to read more is to join people who read. Culture sets the gravity.',
    takeaway: 'Surround yourself with people whose default behaviors are your aspirational ones.',
    practice: "Name one community (online or off) aligned with the identity you're building.",
    minutes: 2,
  },
  {
    id: 13, chapter: '2nd Law · Make it attractive', title: 'Reframe "have to" as "get to"',
    quote: 'Highlight the benefits of avoiding a bad habit to make it seem unattractive.',
    body: "Mindset is a multiplier. \"I have to exercise\" becomes \"I get to move my body in a way most of the world can't.\" The action is the same; the framing changes whether it pulls or pushes.",
    takeaway: 'Edit the sentence you say in your head about the habit.',
    practice: 'Take a habit you resist. Write it as a "get to" sentence.',
    minutes: 2,
  },
  {
    id: 14, chapter: '3rd Law · Make it easy', title: 'Reduce friction',
    quote: 'Behavior is shaped by the path of least resistance.',
    body: "Want to floss? Put the floss on the sink, not in the drawer. Want to skip social media? Log out, delete the app, leave the phone in another room. Each unit of friction removed is a unit of willpower saved.",
    takeaway: 'Make the good behavior 20 seconds easier; make the bad one 20 seconds harder.',
    practice: 'Identify one piece of friction blocking a habit. Remove it today.',
    minutes: 2,
  },
  {
    id: 15, chapter: '3rd Law · Make it easy', title: 'The 2-minute rule',
    quote: 'When you start a new habit, it should take less than two minutes to do.',
    body: '"Read before bed" → "Read one page". "Run 5K" → "Put on running shoes". Master the act of showing up first; scale comes later. A 2-minute version is impossible to skip and just as identity-building.',
    takeaway: 'Optimize for ritual, not result, in the early days.',
    practice: 'Shrink your hardest habit to a 2-minute version. Try it for a week.',
    minutes: 3,
  },
  {
    id: 16, chapter: '3rd Law · Make it easy', title: 'Master the decisive moment',
    quote: 'Every day is made of dozens of decisive moments.',
    body: "You don't skip the gym at 6pm; you skip it at 5:55pm when you sit on the couch. The fork in the road is small and quiet. Win the moment of choice, and the action takes care of itself.",
    takeaway: "Don't fight the habit. Win the 30 seconds before it.",
    practice: 'Identify the decisive moment for one habit. What can stage it for success?',
    minutes: 2,
  },
  {
    id: 17, chapter: '4th Law · Make it satisfying', title: 'Immediate reward beats delayed reward',
    quote: 'What is rewarded is repeated. What is punished is avoided.',
    body: 'The brain prioritizes the present. Habits with delayed rewards (exercise, saving) need a small immediate one bolted on — checking a box, transferring the saved amount to a "fun" account, the visual streak.',
    takeaway: 'Add a small, instant satisfaction to a long-delayed habit.',
    practice: 'Pair one delayed-reward habit with a tiny immediate reward you control.',
    minutes: 3,
  },
  {
    id: 18, chapter: '4th Law · Make it satisfying', title: "Don't break the chain",
    quote: 'Never miss twice.',
    body: "Missing once is an accident. Missing twice is the start of a new habit. The rule isn't perfection; the rule is rapid recovery. Slip Tuesday → show up Wednesday, no matter how small.",
    takeaway: 'Lower the bar dramatically the day after a miss. Just show up.',
    practice: 'Pre-decide your "minimum recovery action" for each habit.',
    minutes: 2,
  },
  {
    id: 19, chapter: '4th Law · Make it satisfying', title: 'Habit tracking',
    quote: "Don't break the chain — the act of tracking itself is satisfying.",
    body: 'A visible streak (X marks on a calendar, dots filling a wall) creates immediate proof of progress. The tracker becomes its own reward; the desire to extend it becomes its own motivation.',
    takeaway: 'A visible record turns the long arc into a daily game you want to win.',
    practice: 'Open the 26-week wall on any habit. The wall is the reward.',
    minutes: 2,
  },
  {
    id: 20, chapter: 'Advanced', title: 'Goldilocks rule',
    quote: 'Humans love challenges, but only those right at the edge of current ability.',
    body: 'Too easy → boredom. Too hard → discouragement. Adherence lives in the narrow band of "manageable difficulty" — about a 4% stretch above your current ability. When a habit gets boring, that\'s the signal to slightly raise it.',
    takeaway: "When boredom hits, don't quit. Step the difficulty up by one notch.",
    practice: "Pick your most automated habit. What's the next 5% upgrade?",
    minutes: 3,
  },
  {
    id: 21, chapter: 'Advanced', title: 'The downside of habits',
    quote: 'Habits + deliberate practice = mastery.',
    body: "Habits make actions automatic, which is great — but automatic also means thoughtless. Mastery requires periodic friction: a coach's eye, a deliberate review, a slightly harder version. The habit is the floor, not the ceiling.",
    takeaway: 'Habits keep you in the game. Reflection makes you better at it.',
    practice: 'Schedule one weekly review of a habit. What needs upgrading?',
    minutes: 3,
  },
  {
    id: 22, chapter: 'Advanced', title: 'Reflect & review',
    quote: 'Reflection prevents drift.',
    body: "Without review, habits decay or freeze. The pros embed two cycles: a weekly review (small course corrections) and an annual review (larger questions of identity). The review is what keeps your habits aligned with who you're becoming.",
    takeaway: 'Schedule the reflection. The unreflected habit drifts.',
    practice: 'Block 20 minutes on Sunday for a weekly review. Use the prompts in this app.',
    minutes: 3,
  },
  {
    id: 23, chapter: 'Advanced', title: 'Accountability contracts',
    quote: 'We are less likely to repeat a bad habit if it is painful or unsatisfying.',
    body: 'A contract with someone you respect — money on the line, public commitment — adds an immediate, social cost to skipping. The cost is what makes the long-term reward feel near.',
    takeaway: 'Make your future self answerable to someone, not just to themselves.',
    practice: 'Pick one habit. Tell one person. Add one consequence.',
    minutes: 3,
  },
  {
    id: 24, chapter: 'Advanced', title: 'Identity must stay flexible',
    quote: 'Hold your identity loosely.',
    body: '"I am a vegan" breaks the day you eat dairy by accident. "I am someone who chooses food intentionally" survives. Build identities that bend.',
    takeaway: 'Pick an identity broad enough to survive a bad day.',
    practice: 'Audit your identity statement. Does it survive a slip? If not, broaden it.',
    minutes: 3,
  },
];

export const CHAPTERS = [...new Set(LESSONS.map((l) => l.chapter))];
